language: ruby
rvm:
- 2.3.3

install: gem install jekyll jekyll-paginate jekyll-seo-tag html-proofer

script: jekyll build && htmlproofer ./_site

# branch whitelist
branches:
  only:
  - master       # test the master branch
  - /pages-(.*)/ # test every branch which starts with "pages-"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
