name: Jared Dillard	
description: Random Thoughts
meta_description: "Jared Dillard, Web Developer from Austin, Texas"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://jareddillard.com'
google_analytics: 'UA-7883601-2 '
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://jareddillard.com'
author:         'Jared Dillard'

permalink: /blog/:title.html
